---
apiVersion: v1
kind: Service
metadata:
  name: broker
  labels:
    app: kafka
spec:
  clusterIP: None  # Headless service for Kafka brokers
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      name: kafka
    - protocol: TCP
      port: 29092
      targetPort: 29092
      name: kafka-internal
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: "broker"
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.0
          ports:
            - containerPort: 9092  # Exposes Kafka external listener
            - containerPort: 29092 # Exposes Kafka internal listener
          env:
            - name: POD_ORDINAL
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
            - name: KAFKA_BROKER_ID
              value: "$(POD_ORDINAL)"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"  # Adjust to your Zookeeper service
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-$(POD_ORDINAL).broker:29092,PLAINTEXT_HOST://localhost:9092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"  # Replication factor for internal topics
            - name: KAFKA_MIN_INSYNC_REPLICAS
              value: "2"  # Minimum in-sync replicas
            - name: KAFKA_LISTENER_PORT
              value: "9092"  # External listener port
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL
              value: "PLAINTEXT"  # Listener protocol
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-$(POD_ORDINAL).broker:29092"
            - name: KAFKA_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_LISTENER_INTERFACE
              value: "0.0.0.0"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL
              value: "PLAINTEXT"
            - name: KAFKA_LISTENER_PORT
              value: "29092"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "3"
  KAFKA_MIN_INSYNC_REPLICAS: "2"